using System.Collections.Generic;
using System.Linq;

namespace ProjectEuler.Solutions
{
/* 
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms. 
*/
    public static class Problem002
    {
        public static IEnumerable<int> GenerateFibonacci()
        {
            var previous = 1;
            var current = 2;
            yield return previous;
            yield return current;
            while (true)
            {
                var newCurrent = previous + current;
                previous = current;
                current = newCurrent;
                yield return current;
            }
        }

        public static int Calculate(int noGreaterThan) =>
            GenerateFibonacci()
                .TakeWhile(x => x < noGreaterThan)
                .Where(x => x % 2 == 0)
                .Sum();
    }
}